create table "public"."Subscriptions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user" text not null,
    "description" text,
    "state" text not null,
    "plan" text not null,
    "billingProviderId" text,
    "modified_at" timestamp with time zone default now(),
    "start_time" timestamp with time zone,
    "end_time" timestamp with time zone
);


alter table "public"."Subscriptions" enable row level security;

CREATE UNIQUE INDEX "Subscriptions_pkey" ON public."Subscriptions" USING btree (id);

alter table "public"."Subscriptions" add constraint "Subscriptions_pkey" PRIMARY KEY using index "Subscriptions_pkey";

alter table "public"."Subscriptions" add constraint "public_Subscriptions_user_fkey" FOREIGN KEY ("user") REFERENCES "Users"(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."Subscriptions" validate constraint "public_Subscriptions_user_fkey";

grant delete on table "public"."Subscriptions" to "anon";

grant insert on table "public"."Subscriptions" to "anon";

grant references on table "public"."Subscriptions" to "anon";

grant select on table "public"."Subscriptions" to "anon";

grant trigger on table "public"."Subscriptions" to "anon";

grant truncate on table "public"."Subscriptions" to "anon";

grant update on table "public"."Subscriptions" to "anon";

grant delete on table "public"."Subscriptions" to "authenticated";

grant insert on table "public"."Subscriptions" to "authenticated";

grant references on table "public"."Subscriptions" to "authenticated";

grant select on table "public"."Subscriptions" to "authenticated";

grant trigger on table "public"."Subscriptions" to "authenticated";

grant truncate on table "public"."Subscriptions" to "authenticated";

grant update on table "public"."Subscriptions" to "authenticated";

grant delete on table "public"."Subscriptions" to "service_role";

grant insert on table "public"."Subscriptions" to "service_role";

grant references on table "public"."Subscriptions" to "service_role";

grant select on table "public"."Subscriptions" to "service_role";

grant trigger on table "public"."Subscriptions" to "service_role";

grant truncate on table "public"."Subscriptions" to "service_role";

grant update on table "public"."Subscriptions" to "service_role";


